export const studentProfile = {
  id: "stu_001",
  name: "Sarah Chen",
  email: "sarah.chen@eduhub.io",
  avatar: "https://i.pravatar.cc/150?img=47",
  joinedAt: "March 2024",
  bio: "Frontend developer passionate about design systems and accessibility.",
  streak: 28,
};

export const stats = {
  enrolled: 12,
  completed: 4,
  inProgress: 8,
  overallProgress: 67,
  hoursLearned: 84.5,
  certificates: 4,
};

export const courses = [
  {
    id: "c_101",
    title: "Advanced React Patterns & Performance",
    instructor: "Dr. Marcus Bennett",
    category: "Web Development",
    thumbnail: "https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=800",
    progress: 68,
    totalLessons: 42,
    completedLessons: 29,
    rating: 4.8,
    duration: "18h 20m",
    lastAccessed: "2 hours ago",
    color: "from-blue-500 to-indigo-600",
  },
  {
    id: "c_102",
    title: "Machine Learning with Python",
    instructor: "Prof. Anika Sharma",
    category: "Data Science",
    thumbnail: "https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=800",
    progress: 34,
    totalLessons: 56,
    completedLessons: 19,
    rating: 4.9,
    duration: "24h 15m",
    lastAccessed: "Yesterday",
    color: "from-purple-500 to-pink-600",
  },
  {
    id: "c_103",
    title: "UI/UX Design Fundamentals",
    instructor: "Elena Rodriguez",
    category: "Design",
    thumbnail: "https://images.unsplash.com/photo-1561070791-2526d30994b8?w=800",
    progress: 92,
    totalLessons: 28,
    completedLessons: 26,
    rating: 4.7,
    duration: "12h 40m",
    lastAccessed: "3 days ago",
    color: "from-orange-500 to-red-600",
  },
  {
    id: "c_104",
    title: "Cloud Architecture on AWS",
    instructor: "James O'Connor",
    category: "DevOps",
    thumbnail: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800",
    progress: 15,
    totalLessons: 38,
    completedLessons: 6,
    rating: 4.6,
    duration: "20h 10m",
    lastAccessed: "5 days ago",
    color: "from-emerald-500 to-teal-600",
  },
  {
    id: "c_105",
    title: "TypeScript Mastery",
    instructor: "Liam Thompson",
    category: "Web Development",
    thumbnail: "https://images.unsplash.com/photo-1579468118864-1b9ea3c0db4a?w=800",
    progress: 100,
    totalLessons: 32,
    completedLessons: 32,
    rating: 4.9,
    duration: "16h 30m",
    lastAccessed: "1 week ago",
    color: "from-cyan-500 to-blue-600",
  },
  {
    id: "c_106",
    title: "Figma for Product Designers",
    instructor: "Priya Patel",
    category: "Design",
    thumbnail: "https://images.unsplash.com/photo-1609921212029-bb5a28e60960?w=800",
    progress: 100,
    totalLessons: 24,
    completedLessons: 24,
    rating: 4.8,
    duration: "10h 15m",
    lastAccessed: "2 weeks ago",
    color: "from-pink-500 to-rose-600",
  },
];

export const lessonsByCourse = {
  c_101: [
    {
      id: "l_01", title: "Welcome & Course Overview",
      duration: "5:20", completed: true, type: "video",
      videoUrl: "https://sample-videos.com/video.mp4",
      description: "An introduction to the course structure and goals.",
    },
    { id: "l_02", title: "Setting Up the Dev Environment", duration: "12:45", completed: true, type: "video",
      description: "Install all required tooling: Node, VS Code, extensions." },
    { id: "l_03", title: "Project Structure Deep Dive", duration: "8:30", completed: true, type: "video",
      description: "Understand folder layouts and conventions." },
    { id: "l_04", title: "Component Composition Patterns", duration: "22:10", completed: true, type: "video",
      description: "Learn compound components and slot patterns." },
    { id: "l_05", title: "Render Props Explained", duration: "18:42", completed: false, type: "video", current: true,
      description: "Master the render props pattern with practical examples." },
    { id: "l_06", title: "Higher-Order Components", duration: "25:30", completed: false, type: "video",
      description: "When and how to use HOCs in modern React." },
    { id: "l_07", title: "Custom Hooks Deep Dive", duration: "30:15", completed: false, type: "video",
      description: "Build reusable logic with custom hooks." },
    { id: "l_08", title: "Quiz: Patterns Review", duration: "10:00", completed: false, type: "quiz",
      description: "Test your understanding of the patterns covered." },
    { id: "l_09", title: "React.memo Strategies", duration: "20:00", completed: false, type: "video",
      description: "Optimizing re-renders effectively." },
    { id: "l_10", title: "Virtualization with react-window", duration: "28:22", completed: false, type: "video",
      description: "Handle large lists performantly." },
  ],
};

export const assignments = [
  {
    id: "a_1", title: "Build a Custom useDebounce Hook",
    course: "Advanced React Patterns", dueDate: "2025-01-18", status: "pending",
    priority: "high", points: 100, submittedAt: null,
    description: "Create a reusable debounce hook and demonstrate its use in a search component.",
  },
  {
    id: "a_2", title: "Linear Regression Implementation",
    course: "Machine Learning with Python", dueDate: "2025-01-22", status: "pending",
    priority: "medium", points: 150, submittedAt: null,
    description: "Implement linear regression from scratch using NumPy.",
  },
  {
    id: "a_3", title: "Design System Component Library",
    course: "UI/UX Design Fundamentals", dueDate: "2025-01-12", status: "submitted",
    priority: "medium", points: 120, submittedAt: "2025-01-10",
    description: "Create a complete design system with Figma components.",
  },
  {
    id: "a_4", title: "Deploy a Scalable Web App",
    course: "Cloud Architecture on AWS", dueDate: "2025-01-25", status: "pending",
    priority: "low", points: 200, submittedAt: null,
    description: "Deploy a multi-tier application using AWS services.",
  },
  {
    id: "a_5", title: "TypeScript Generics Challenge",
    course: "TypeScript Mastery", dueDate: "2025-01-05", status: "graded",
    priority: "medium", points: 100, grade: 94, submittedAt: "2025-01-04",
    description: "Solve 10 advanced generic type challenges.",
  },
  {
    id: "a_6", title: "Portfolio Redesign in Figma",
    course: "Figma for Product Designers", dueDate: "2024-12-28", status: "graded",
    priority: "low", points: 80, grade: 88, submittedAt: "2024-12-26",
    description: "Redesign your personal portfolio using modern principles.",
  },
];

export const certificates = [
  {
    id: "cert_1", courseTitle: "TypeScript Mastery",
    instructor: "Liam Thompson", issueDate: "2025-01-05",
    grade: "A+", unlocked: true, credentialId: "EH-TS-2025-0042",
  },
  {
    id: "cert_2", courseTitle: "Figma for Product Designers",
    instructor: "Priya Patel", issueDate: "2024-12-28",
    grade: "A", unlocked: true, credentialId: "EH-FG-2024-1108",
  },
  {
    id: "cert_3", courseTitle: "JavaScript Fundamentals",
    instructor: "Marcus Bennett", issueDate: "2024-11-15",
    grade: "A", unlocked: true, credentialId: "EH-JS-2024-0937",
  },
  {
    id: "cert_4", courseTitle: "HTML & CSS Essentials",
    instructor: "Elena Rodriguez", issueDate: "2024-10-02",
    grade: "A-", unlocked: true, credentialId: "EH-HC-2024-0651",
  },
  {
    id: "cert_5", courseTitle: "Advanced React Patterns",
    instructor: "Dr. Marcus Bennett", progress: 68,
    unlocked: false, requiredProgress: 100,
  },
  {
    id: "cert_6", courseTitle: "Machine Learning with Python",
    instructor: "Prof. Anika Sharma", progress: 34,
    unlocked: false, requiredProgress: 100,
  },
];

export const weeklyProgress = [
  { day: "Mon", hours: 2.5, lessons: 4 },
  { day: "Tue", hours: 3.1, lessons: 6 },
  { day: "Wed", hours: 1.8, lessons: 3 },
  { day: "Thu", hours: 4.2, lessons: 7 },
  { day: "Fri", hours: 2.9, lessons: 5 },
  { day: "Sat", hours: 5.1, lessons: 9 },
  { day: "Sun", hours: 3.4, lessons: 6 },
];

export const monthlyProgress = [
  { month: "Aug", hours: 42, courses: 1 },
  { month: "Sep", hours: 58, courses: 2 },
  { month: "Oct", hours: 71, courses: 2 },
  { month: "Nov", hours: 62, courses: 3 },
  { month: "Dec", hours: 85, courses: 4 },
  { month: "Jan", hours: 94, courses: 4 },
];

export const notifications = [
  { id: "n_1", type: "assignment", title: "New assignment posted",
    message: "Dr. Bennett added 'Custom Hook Challenge' to React Patterns",
    time: "10 min ago", unread: true },
  { id: "n_2", type: "grade", title: "Quiz graded: 94%",
    message: "Great work on the ML Foundations quiz!",
    time: "1 hour ago", unread: true },
  { id: "n_3", type: "announcement", title: "Live Q&A tomorrow",
    message: "Join the AWS live session at 3:00 PM EST",
    time: "5 hours ago", unread: false },
  { id: "n_4", type: "certificate", title: "Certificate unlocked!",
    message: "You earned the TypeScript Mastery certificate",
    time: "2 days ago", unread: false },
];